name: release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: false
jobs:
  create-release-candidate-branch:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v4
      - name: set version from source code
        run: |
          awk '/version/ {print "version="$2+1}' README.md >> "$GITHUB_ENV"
      - name: copy branch from tip and push as a release branch
        run: |
          git branch -c release/$version-0
          git push origin release/$version-0

  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set version from source code
        if: inputs.version == ''
        run: |
          awk '/version/ {print "version="$2+1}' README.md >> "$GITHUB_ENV"
      - name: set version from inputs
        if: inputs.version != ''
        run: |
          echo "version=${{ inputs.version }}" >> "$GITHUB_ENV"
      - name: Setup git
        run: |
          git config --global user.name "Safello Github Action runner"
          git config --global user.email "noreply@safello.com"
          git checkout -b bump-version-$version
      - name: update version
        run: |
          sed -i "s/version.*/version $version/" README.md
      - name: commit
        run: |
          git add README.md
          git commit -m "[AUTO-COMMIT] Bump version"
          git push origin bump-version-$version
      - name: create pr
        run: |
          gh pr create -B main -H bump-version-$version --title "Bump version to $version" --body "Created by Github Action"
        env:
          GH_TOKEN: ${{ github.token }}
