name: release
on:
  workflow_dispatch:
    inputs:
      version-major:
        type: string
        required: false
      version-minor:
        type: string
        required: false
jobs:
  create-release-candidate-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set version from source code
        run: |
          sed -E -n 's/^version (0|[1-9][[:digit:]]*)\.(0|[1-9][[:digit:]]*)/MAJOR=\1\nMINOR=\2/p' README.md >> "$GITHUB_ENV"
      - name: copy branch from tip and push as a release branch
        run: |
          git branch -c release/$MAJOR-$MINOR
          git push origin release/$MAJOR-$MINOR

  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set version from source code
        run: |
          echo MAJOR=$(($(sed -E -n 's/^version (0|[1-9][[:digit:]]*)\.(0|[1-9][[:digit:]]*)/\1/p' README.md))) >> "$GITHUB_ENV"
          echo MINOR=$(($(sed -E -n 's/^version (0|[1-9][[:digit:]]*)\.(0|[1-9][[:digit:]]*)/\2/p' README.md) + 1 )) >> "$GITHUB_ENV"
      - name: set major version from inputs
        if: inputs.version-major != ''
        run: |
          echo "MAJOR=${{ inputs.version-major }}" >> "$GITHUB_ENV"
      - name: set minor version from inputs
        if: inputs.version-minor != ''
        run: |
          echo "MINOR=${{ inputs.version-minor }}" >> "$GITHUB_ENV"
      - name: Setup git
        run: |
          git config --global user.name "Safello Github Action runner"
          git config --global user.email "noreply@safello.com"
          git checkout -b bump-version-$MAJOR-$MINOR
      - name: update version
        run: |
          sed -i "s/version.*/version $MAJOR.$MINOR/" README.md
      - name: commit
        run: |
          git add README.md
          git commit -m "[AUTO-COMMIT] Bump version"
          git push origin bump-version-$version
      - name: create pr
        run: |
          gh pr create -B main -H bump-version-$version --title "Bump version to $version" --body "Created by Github Action"
        env:
          GH_TOKEN: ${{ github.token }}
