---

# Bump version and create release branch
#
# If this workflow is triggered from the 'main' branch, it will create a new
# branch called 'release/X.Y.Z', where X.Y.Z is the current version. Afterwards
# it will bump the minor version and create a pull request for that commit.
#
# Using the 'bump-major' option you can bump the major version instead of the
# minor. The minor will then get set to 0.
#
# If this workflow is triggered from a 'release/Z.Y.Z' branch, it will bump the
# patch version.

name: Bump version
on:
  workflow_dispatch:
    inputs:
      bump-major:
        type: boolean
        required: true
        default: false
jobs:
  create-release-candidate-branch:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v4
      - name: read version from source code
        run: |
          sed -E -n 's/^version (0|[1-9][[:digit:]]*)\.(0|[1-9][[:digit:]]*)/MAJOR=\1\nMINOR=\2/p' README.md >> "$GITHUB_ENV"
      - name: copy branch from tip and push as a release branch
        run: |
          git branch -c release/$MAJOR-$MINOR
          git push origin release/$MAJOR-$MINOR

  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set version from source code and bump Patch version
        run: |
          echo MAJOR=$(($(sed -E -n 's/^version (0|[1-9][[:digit:]]*)\.(0|[1-9][[:digit:]]*)\.(0|[1-9][[:digit:]]*)/\1/p' README.md))) >> "$GITHUB_ENV"
          echo MINOR=$(($(sed -E -n 's/^version (0|[1-9][[:digit:]]*)\.(0|[1-9][[:digit:]]*)\.(0|[1-9][[:digit:]]*)/\2/p' README.md))) >> "$GITHUB_ENV"
          echo PATCH=$(($(sed -E -n 's/^version (0|[1-9][[:digit:]]*)\.(0|[1-9][[:digit:]]*)\.(0|[1-9][[:digit:]]*)/\3/p' README.md) + 1 )) >> "$GITHUB_ENV"
      - name: Bump Minor version
        if: github.ref_name == 'main'
        run: |
          echo MINOR=$(( $MAJOR + 1)) >> "$GITHUB_ENV"
          echo PATCH=0 >> "$GITHUB_ENV"
      - name: Bump Major version
        if: github.ref_name == 'main' && inputs.bump-major == true
        run: |
          echo MAJOR=$(( $MAJOR + 1)) >> "$GITHUB_ENV"
          echo MINOR=0 >> "$GITHUB_ENV"
      - name: Setup git
        run: |
          git config --global user.name "Safello Github Action runner"
          git config --global user.email "noreply@safello.com"
          git checkout -b bump-version-$MAJOR-$MINOR-$PATCH
      - name: update version
        run: |
          sed -i "s/version.*/version $MAJOR.$MINOR.$PATCH/" README.md
      - name: commit
        run: |
          git add README.md
          git commit -m "[AUTO-COMMIT] Bump version"
          git push origin bump-version-$MAJOR-$MINOR-$PATCH
      - name: create pr
        run: |
          gh pr create -B ${{ github.ref_name }} -H bump-version-$MAJOR-$MINOR --title "Bump version to $MAJOR.$MINOR" --body "Created by Github Action"
        env:
          GH_TOKEN: ${{ github.token }}
