name: release
on: [ workflow_dispatch ]
jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup git
        run: |
          git config --global user.name "Safello Github Action runner"
          git config --global user.email "noreply@safello.com"
          git checkout -b bump-version
      - name: update version
        run: |
          awk '/version/ {$2+=1} 1' README.md > tmp
          mv tmp README.md
      - name: commit
        run: |
          git add README.md
          git commit -m "[AUTO-COMMIT] Bump version"
          git push origin bump-version
      - name: create pr
        run: |
          gh pr create -B main -H bump-version --title "Bump version PR" --body "Created by Github Action"
        env:
          GH_TOKEN: ${{ github.token }}
